name: Supabase

run-name: Supabase - ${{ github.event.head_commit.message || github.event.pull_request.title || 'Manual' }}

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      # - uses: actions/checkout@v4

      # - uses: supabase/setup-cli@v1
      #   with:
      #     version: latest

      # - name: Link to Supabase project
      #   run: supabase link --project-ref $SUPABASE_PROJECT_ID

      # - name: Push database migrations
      #   run: supabase db push
